FROM ubuntu:xenial

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libcurl4-openssl-dev python3-pip python3 libboost-python-dev python3-dev && \
    rm -rf /var/lib/apt/lists/* 
    
RUN pip3 install --upgrade pip    
RUN pip3 install setuptools
RUN pip3 install ptvsd==4.1.1a11
COPY requirements.txt ./
RUN pip3 install -r requirements.txt

COPY . .

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

CMD [ "python3", "-u", "./main.py" ]